baseURL: /
languageCode: "en-us"
title: Creative Coding Hackspace
theme: book

publishDir: public

enableGitInfo: true
disableKinds: ['taxonomy', 'taxonomyTerm']

params:
  BookRepo: https://github.com/jamesb93/huddersfield-creative-coding
  BookSearch: true
  BookMenuBundle: /menu
  BookDateFormat: 'Jan 2, 2006'
  BookToC: false
  BookSearch: false

markup:
  goldmark:
    renderer:
      unsafe: true
