baseURL: /
languageCode: "en-us"
title: Huddersfield Creative Coding
theme: book

publishDir: public

enableGitInfo: false
params:
  BookToC: false
  BookRepo: https://github.com/jamesb93/huddersfield-creative-coding
  BookSearch: true
