baseURL: /
languageCode: "en-us"
title: Huddersfield Creative Coding Lab
theme: book

publishDir: docs

enableGitInfo: true
params:
  BookToC: false
  BookRepo: https://github.com/jamesb93/huddersfield-creative-coding
  BookSearch: true
